CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB; 

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.BRONZE; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.SILVER; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.GOLD; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.CONTROL; 

-- Bronze: raw representation 
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE.CUSTOMERS ( 
    CUSTOMER_ID NUMBER, 
    FIRST_NAME VARCHAR(100), 
    LAST_NAME VARCHAR(100), 
    EMAIL VARCHAR(200), 
    CITY VARCHAR(100), 
    STATE VARCHAR(100), 
    COUNTRY VARCHAR(100), 
    SOURCE_FILE_NAME VARCHAR(500), 
    LOAD_TIMESTAMP TIMESTAMP_NTZ, 
    BATCH_ID VARCHAR(100) 
);