CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB; 

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.BRONZE; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.SILVER; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.GOLD; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.CONTROL; 
