CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB; 

CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.BRONZE; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.SILVER; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.GOLD; 
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_DB.CONTROL; 

SELECT CURRENT_WAREHOUSE();
SHOW WAREHOUSES;
SELECT CURRENT_USER();
SHOW STAGES IN SCHEMA ECOMMERCE_DB.BRONZE;
SELECT CURRENT_ACCOUNT(),CURRENT_REGION();

SELECT
    query_id,
    query_text,
    execution_status,
    start_time
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY(
    RESULT_LIMIT => 100
))
ORDER BY start_time DESC;