-- Bronze: raw representation 
CREATE TABLE IF NOT EXISTS ECOMMERCE_DB.BRONZE.CUSTOMERS ( 
    CUSTOMER_ID NUMBER, 
    FIRST_NAME VARCHAR(100), 
    LAST_NAME VARCHAR(100), 
    EMAIL VARCHAR(200), 
    CITY VARCHAR(100), 
    STATE VARCHAR(100), 
    COUNTRY VARCHAR(100), 
    SOURCE_FILE_NAME VARCHAR(500), 
    LOAD_TIMESTAMP TIMESTAMP_NTZ, 
    BATCH_ID VARCHAR(100) 
);

CREATE OR REPLACE FILE FORMAT BRONZE.CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;

USE DATABASE ECOMMERCE_DB;
USE SCHEMA BRONZE;

DESC FILE FORMAT ECOMMERCE_DB.BRONZE.CSV_FORMAT;

CREATE OR REPLACE STORAGE INTEGRATION S3_ECOMMERCE_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470451076022:role/amz-EDPRP-Snowflake-S3-Role-Singapore'
STORAGE_ALLOWED_LOCATIONS = (
    's3://amz-s3-data-snow-ap-singapore/raw/customers/'
);

DESC STORAGE INTEGRATION S3_ECOMMERCE_INTEGRATION;
/* 
STORAGE_AWS_IAM_USER_ARN ='arn:aws:iam::192929863221:user/ebt62000-s';
STORAGE_AWS_ROLE_ARN='arn:aws:iam::470451076022:role/amz-EDPRP-Snowflake-S3-Role-Singapore'
STORAGE_AWS_EXTERNAL_ID = 'AO72901_SFCRole=4_i9vxDABc11C0AbLFHPAmYDvyQCk=';
*/

CREATE OR REPLACE STAGE ECOMMERCE_DB.BRONZE.S3_CUSTOMERS_STAGE
URL = 's3://amz-s3-data-snow-ap-singapore/raw/customers/'
STORAGE_INTEGRATION = S3_ECOMMERCE_INTEGRATION
FILE_FORMAT = ECOMMERCE_DB.BRONZE.CSV_FORMAT;


LIST @ECOMMERCE_DB.BRONZE.S3_CUSTOMERS_STAGE;

select CURRENT_REGION();

select $1 from @ECOMMERCE_DB.BRONZE.S3_CUSTOMERS_STAGE;
